# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-24 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tfilm',
            old_name='loc',
            new_name='loc_id',
        ),
        migrations.RenameField(
            model_name='tfilm',
            old_name='sub_class',
            new_name='sub_class_id',
        ),
        migrations.RenameField(
            model_name='tfilm',
            old_name='type',
            new_name='type_id',
        ),
        migrations.RenameField(
            model_name='traty',
            old_name='film',
            new_name='film_id',
        ),
        migrations.RenameField(
            model_name='tres',
            old_name='film',
            new_name='film_id',
        ),
        migrations.RenameField(
            model_name='tsubclass',
            old_name='catelog',
            new_name='catelog_id',
        ),
        migrations.RenameField(
            model_name='ttype',
            old_name='subclass',
            new_name='subclass_id',
        ),
        migrations.AlterField(
            model_name='tfilm',
            name='cate_log_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='films', to='home.TCateLog'),
        ),
    ]
